### ISSUE TITLE
Remove label from legend

### ISSUE THREAD

**Issue by DanielAndreasen** [phn/lineid_plot#7]
Hi,

First of all, thanks for this nice package.

I have a request. When I overplot a couple of spectra on top of each other I use the `plt.legend` to show the labels. But when used with `lineid_plot`, all the labels of the lines are showed as well. Is there a way to remove those labels?
![lineid_plot](https://cloud.githubusercontent.com/assets/4519017/20711947/0ce92d40-b63a-11e6-8b60-a4cf0cd73215.png)

**Comment by phn** [comment]
Hello,

Glad to know that you find this useful.

The program adds a label to all the spectrum identification lines so that it becomes easy to identify each line. The ``plt.legend()`` function by default uses all artists with a label. So that is why you  see the labels for line identifications in the legend.

I would suggest that you use the feature described at http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.legend that allows one to manually specify both artists and their label.

In the graph you have attached it seems like you only want legend to display  "sun", "telluric" and "star", which I assume are the three spectra shown. So you could try calling legend with the three spectra and their labels. An example is the documentation page linked above.

Hope this helps.

Regards,
Prasanth

**Comment by DanielAndreasen** [comment]
Hello Prasanth,

Thanks for your quick reply. The "problem" is that my labels can be dynamic, so it is not straightforward to assign. I can do it with enough `if` statements, but who has the time.
I took the liberty to clone your project and simply remove the labels. I understand if you don't want to merge it, so I will not open a pull request.

Regards,
Daniel

**Comment by phn** [comment]
Hello,

I will look into this during the weekend and see if I can add an option to remove labels, so that it will work for your use case. I haven't looked at the source code in a while so can't tell off the top of my head what parts of the code will be affected by such a change. 

Thanks for reporting this use case.

Regards,
Prasanth

**Comment by DanielAndreasen** [comment]
Have a look at my repository then. There you can see the two lines I commented. It should be easy enough to add a `show_labels=True` be default.

**Comment by phn** [comment]
Hello,

Turns out that the code in the module doesn't use the artist-labels anywhere. So the fix was not difficult.

I added a new option "add_label_to_artists" to ``plot_line_ids``, which is set to True by default. If False then labels are not added to artists.

I have changed version to 0.4 and will shortly push it to pypi.

Thanks again.

Regards,

Prasanth

**Comment by DanielAndreasen** [comment]
Great, thanks for the update 👍

**Comment by phn** [comment]
Hello,

Please use version 0.5 on pypi. ``pip install`` without version number will also work.

I made some mistake that made it impossible to get 0.4 uploaded on to pypi. 

Regards,
Prasanth
