### ISSUE TITLE
Installing requires numpy and matplotlib

### ISSUE THREAD

**Issue by saimn** [phn/lineid_plot#9]
Because of the lineid_plot import to get the version, in the `setup.py`, numpy and matplotlib need to be installed before lineid_plot. This complicates the use of lineid_plot in automated ci testing. Would you agree to change this, either reading (manually) the version from the file, with a regex, or duplicating the version ?

Also it would be good to have wheels if you can make a new release to fix this issue. I can propose a patch if it helps.

**Comment by phn** [comment]
Hello Simon,

I agree with your suggestions for changes.

1) Do you have a preference for how to put version information in a different place? The simplest thing seems to be to just duplicate it in lineid_plot.py and setup.py. We can add a RELEASE_TODO.md file that documents what to do before a release. Since the code base is very simple this shouldn't complicate things.

2) Yes, I would appreciate a pull request for adding wheel support!

Regards,
Prasanth

**Comment by saimn** [comment]
Hi,
Ok, I will try to submit a PR soon! For the version there is no standard way to do it, usually I put it in a Python file which can be imported from the `__init__.py` or called with `exec` from the setup or from the doc `conf.py`: https://packaging.python.org/guides/single-sourcing-package-version/
But it's also fine to duplicate if you prefer the simple way.
